### ISSUE TITLE
Inputs other than CIF?

### ISSUE THREAD

**Issue by dextorious** [lieff/minih264#5]
Hi! This is a very impressive project, kudos for pulling it off. :-)

Since the only example given uses CIF input with all of the restrictions that implies (352x288 resolution, 30000/1001 framerate, YCbCr color representation, etc.), I'm wondering to what extent those restrictions are currently hard coded into the encoder. I'd love to use minih264 in a project I'm writing as a backup option for cases when ffmpeg is not available, but that requires dealing with arbitrary resolution frames of RGBA images (which I can, of course, transform on the fly, but the resolution part isn't flexible). Is that something that would be doable with reasonable effort, or am I pushing too far beyond the scope of your intentions for this project?

**Comment by lieff** [comment]
Hi :)
Sample application supports any input resolution. It tries guess it from file name here:
```
static const frame_size_descriptor_t g_frame_size_descriptor[] =
{
    {"sqcif",  128,   96},
    { "qvga",  320,  240},
    { "svga",  800,  600},
    { "4vga", 1280,  960},
    { "sxga", 1280, 1024},
    {  "xga", 1024,  768},
    {  "vga",  640,  480},
    { "qcif",  176,  144},
    { "4cif",  704,  576},
    { "4sif",  704,  480},
    {  "cif",  352,  288},
    {  "sif",  352,  240},
    {  "pal",  720,  576},
    { "ntsc",  720,  480},
    {   "d1",  720,  480},
    {"16cif", 1408, 1152},
    {"16sif", 1408,  960},
    { "720p", 1280,  720},
    {"4SVGA", 1600, 1200},
    { "4XGA", 2048, 1536},
    {"16VGA", 2560, 1920},
    {"16VGA", 2560, 1920},
    {NULL, 0, 0},
};

/**
*   Guess image size specification from ASCII string.
*   If string have several specs, only last one taken.
*   Spec may look like "352x288" or "qcif", "cif", etc.
*/
static int guess_format_from_name(const char *file_name, int *w, int *h)
```

RGB do not supported directly in h264 format. RGB->YUV converter is needed and do not included in sample app. I suggest using https://github.com/lemenkov/libyuv to do the conversion.

**Comment by lieff** [comment]
fps is more interesting question, in h264 it can be encoded in VUI parameters block in SPS, but it's optional and minih264 do not encodes that block. So there no information stored in h264 stream about fps, and there no timestamps per frame either. This information should be added at packetization step (PES, TS, MP4 etc). So minih264 is fully fps agnostic and you must manually calculate frame budget from fps what you want. Here where it's calculated in sample app:
```Only place where fps used in minimp4 - it's rate control, and it's
            if (cmdline->kbps)
            {
                run_param.desired_frame_bytes = cmdline->kbps*1000/8/30;
                run_param.qp_min = 10;
                run_param.qp_max = 50;
            } else
```

API somewhat documented in header itself:
https://github.com/lieff/minih264/blob/master/minih264e.h#L22

**Comment by dextorious** [comment]
Awesome, thank you for the comprehensive response. This should be enough to get me started. :)
