### ISSUE TITLE
how to set temporal layer size to 3?

### ISSUE THREAD

**Issue by richardor** [lieff/minih264#6]
`
    // Number of SVC layers:
    // 1 = AVC
    // 2 = SVC with 2-layers of spatial scalability
    int num_layers;
`
if I want to encode 3 temporal layers, 1 spatial layer, what should I do?

**Comment by richardor** [comment]
@lieff

**Comment by lieff** [comment]
Hi)
You need num_layers=1 and enable ENABLE_TEMPORAL_SCALABILITY in minih264e_test.c sample which uses frame_type = H264E_FRAME_TYPE_CUSTOM; and long_term_idx_update/long_term_idx_use indexes.
By manipulating long_term_idx_update/long_term_idx_use you can achieve any prediction pattern.

**Comment by richardor** [comment]
@lieff 
I did it, and run "./h264enc_x86 vector/foreman.cif".  the output file is out.264.
i canot see any svc extensions in the pps/sps.

![image](https://user-images.githubusercontent.com/2875711/58250512-27ed3680-7d94-11e9-8324-ab96f735d8c7.png)
![image](https://user-images.githubusercontent.com/2875711/58250536-30de0800-7d94-11e9-97f8-fcb6c8dccf58.png)

**Comment by richardor** [comment]
[out.264.zip](https://github.com/lieff/minih264/files/3211937/out.264.zip)

**Comment by richardor** [comment]
can you post your temporal svc file here?
thank you!

**Comment by lieff** [comment]
Such temporal scalability is the AVC feature. It do not use SVC specific features and compatible with the AVC decoders.
You can read more info here:
http://www.ti.com/lit/an/sprabg3/sprabg3.pdf
https://www.hhi.fraunhofer.de/en/departments/vca/research-groups/image-video-coding/research-topics/svc-extension-of-h264avc/temporal-scalability-in-h264avc.html

Only spatial scalability enables SVC bitstream generation.

**Comment by richardor** [comment]
> Hi)
> You need num_layers=1 and enable ENABLE_TEMPORAL_SCALABILITY in minih264e_test.c sample which uses frame_type = H264E_FRAME_TYPE_CUSTOM; and long_term_idx_update/long_term_idx_use indexes.
> By manipulating long_term_idx_update/long_term_idx_use you can achieve any prediction pattern (and any temporal layers pattern in the particular case).

I did it as you said,  and  I found the temporal layers is just 2. Am I right?
thank you!

**Comment by lieff** [comment]
Yes, default temporal layers number in example is 2, IIRC you can change it to 3 by modify logmod = 1 to logmod = 2.
