### ISSUE TITLE
About decoder.

### ISSUE THREAD

**Issue by msnh2012** [lieff/minih264#7]
Hi,bro.  Thx for your awesome work. Do you have plan to create a decoder which is headed only.  And can you recommend another single decoder lib which can decode your minih264. Thx :D.

**Comment by lieff** [comment]
I think about to create decoder which is not fully baseline\high profile compatible, but compatible with minih264 encoder (because encoder already contains large part of decoder).
Fully compatible decoder is much harder, especially mini, because we need support all standard features.
