### ISSUE TITLE
About Cross-platform

### ISSUE THREAD

**Issue by oooooome** [lieff/minih264#8]
Hello, I want to run minih264 on a Mac system. Does it support cross-platform use?

**Comment by lieff** [comment]
Hi) Yes, it should work on MacOs.

**Comment by oooooome** [comment]
I will try, thx

**Comment by oooooome** [comment]
I am running this encoder on Windows now, and some functions cannot work properly. 
`event_create`, `thread_create`, `event_wait`, `event_set` 
I think it may be missing some lib or header file, is it convenient to tell me?
My environment is Virtual Studio 2019, and the compiler is cmake.

**Comment by lieff** [comment]
This is system-dependent thread functions located in system.c. They are not needed if H264E_MAX_THREADS=0 during sample compilation.

**Comment by oooooome** [comment]
Thanks for your help. I have successfully run the encoder.
But I have another problem. If I want to change the number of temporal layers or spatial layers individually, which parameters do I need to change?

**Comment by lieff** [comment]
Spatial layers can be changed here:
```

**Comment by oooooome** [comment]
I did what you said, and the encoded video did change. I use JSVM to extract the bitstream of the encoded 264 file, but it seems to have no effect

**Comment by oooooome** [comment]
I hope to get a svc video stream that contains all the time and space layers. Can minih264 be implemented?

**Comment by lieff** [comment]
Yes, spatial layers easy to detect, you should see 2x lower resolution with num_layers = 2 using vlc player for example. For spatial layers slice_headers should be analysed using some stream dumper, can't tell easy way to detect it, just checked myself and see that it's working too.
Can you attach you changes and build options?

**Comment by oooooome** [comment]
I made the following changes

minih264e.h
```
#ifndef H264E_MAX_THREADS
#   define H264E_MAX_THREADS 0
#endif
```
minih264e_test.c
`#define ENABLE_TEMPORAL_SCALABILITY 1`

and These are the input parameters
```
cmdline->gop = DEFAULT_GOP;
    cmdline->qp = DEFAULT_QP;
    cmdline->max_frames = DEFAULT_MAX_FRAMES;
    cmdline->kbps = 2048;
    cmdline->denoise = DEFAULT_DENOISE;
    cmdline->gen = 0;
    cmdline->input_file = "input.yuv";
    cmdline->output_file = "output.264";
    cmdline->stats = 1;
    cmdline->threads = 1;
    cmdline->psnr = 1;
    cmdline->speed = 5;
```

I set `num_layers` to 2 and `logmod` to 2. The frame size change to 1/2 compared with the source file, but the frame rate dosent change.
```
#if H264E_SVC_API
    create_param.num_layers = 2;
    create_param.inter_layer_pred_flag = 1;
    create_param.inter_layer_pred_flag = 0;
#endif
```
`int level, logmod = 2;`

**Comment by oooooome** [comment]
[output.zip](https://github.com/lieff/minih264/files/5606508/output.zip)

**Comment by lieff** [comment]
No need to change logmod = 2, logmod = 1 means 2 layers.
Frame rate should not change, that's correct, you can't detect it this way. Because when you decode all frames (and there no obstacle to decode all frames in base layer since it's normal h264 AVC) - you get original fps. But system that use this stream CAN drop 1/2 frames and get 1/2 frame rate.
Same for spatial scalability if you decode both base layer + SVC layers - you get original resolution.
VLC do not supports SVC layers, that's why you get 1/2 resolution, but it supports droppable frames in base layer.

**Comment by lieff** [comment]
Closing since question answered.
